### ISSUE TITLE
Suggestion to add InertiaJs version with Bootstrap

### ISSUE THREAD

**Issue by souravtah** [LaravelDaily/Larastarters#51]

**Comment by PovilasKorop** [comment]
@souravtah since default Laravel UI doesn't have Inertia version, for us it would be quite a big effort to create it from scratch.

For Tailwind, we used Laravel Breeze that has Inertia version.

For Bootstrap, at the moment we don't have that much time available. But if anyone wants to take this task, we would accept a Pull Request.
