### ISSUE TITLE
Configuration with vite

### ISSUE THREAD

**Issue by ghost** [LaravelDaily/Larastarters#80]
I use Larastarters all the time, it gets me running with a new project in no time, but now with vite i don´t understand what kind of configuration i should use because if i go to the documentation and follow all those steps AFTER install this package i always get:

Configuration "resources/js/app.js" does not exist.

but it´s there!.

@PovilasKorop could you help with this one?

**Comment by PovilasKorop** [comment]
@japasanto larastarters bootstrap is based on Laravel UI which is currently not working with Vite at all, we can't do much until that fix is released. See issue #78

**Comment by japasanto** [comment]
Hi povilas

   It’s kinda odd why they don’t fix this, because meanwhile one can use the breeze starter kit and everything works, but it adds tailwind and alpine js and innertia, which I don’t want to use, I prefer it simple.

Thanks for answering.

João santo

No dia 12/07/2022, às 19:55, PovilasKorop ***@***.***> escreveu:

﻿

@japasanto<https://github.com/japasanto> larastarters bootstrap is based on Laravel UI which is currently not working with Vite at all, we can't do much until that fix is released. See issue #78<https://github.com/LaravelDaily/Larastarters/issues/78>

**Comment by PovilasKorop** [comment]
@japasanto they officially support only Breeze and Jetstream, Laravel UI based on Bootstrap is the old method which they promised to "keep alive" but it's never even mentioned in the docs. 

So we need to wait when they have time to work on Laravel UI, which is totally not their priority. 

That said, it's open source and everyone can contribute, so you can join the discussion there: https://github.com/laravel/ui/pull/228

**Comment by japasanto** [comment]
Hi everyone

  I think i manage something interesting, so here are the steps i took:

**vite.config.js**

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import path from 'path';

export default defineConfig({
    plugins: [
        laravel([
            'resources/sass/app.scss',
            'resources/js/app.js',
        ]),
    ],
    resolve: {
        alias: {
            '~bootstrap': path.resolve(__dirname, 'node_modules/bootstrap'),
        }
    },
});
```

**app.js**

```
import('@tabler/core/src/js/tabler.js');
import('./bootstrap');
```

**app.scss**

```
// Tabler

$assets-base: "../../../dist" !default;

@import '@tabler/core/src/scss/tabler';
```

**guest.blade and app.blade**

```
{{--    <link href="{{ asset('css/app.css') }}" rel="stylesheet">--}}
@vite(['resources/sass/app.scss', 'resources/js/app.js'])
```


In my bootstrap.js i changed require bootstrp to import bootstrap, but it is complaning about axios:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'headers')

can you help with this last one?

**Comment by RoduanKD** [comment]
Update: Laravel/UI v4 is released
here's what I did to make it work:
- `composer require laraveldaily/larastarters`
- `php artisan larastarter:install`
- in my case I used Laravel UI with Tabler
- update laravel ui version with `composer require laravel/ui:^4.0`
- after that, an error occurred from bootstrap that can be fixed by downgrading it to exactly `v5.3.1`  [link](https://github.com/twbs/bootstrap/issues/36785)
- then all that is left is `npm i && npm run dev`

you can also check this [commit](https://github.com/RoduanKD/markit/commit/e217025f89c2ceece566d4e3706fa39aeefa4480)

**Comment by krekas** [comment]
@RoduanKD can you make pr?

**Comment by PovilasKorop** [comment]
@krekas I think it would be better if you take care of it a bit deeper: try to make a PR from @RoduanKD commit - https://github.com/RoduanKD/markit/commit/e217025f89c2ceece566d4e3706fa39aeefa4480 - and also we need to test ALL the Bootstrap-based themes with it, cause some of them may not work at all, with the new changes.

So please dive a bit deeper, and fingers crossed this will be an easy PR with no "surprises" :)

**Comment by RoduanKD** [comment]
I've created a [pull request](https://github.com/LaravelDaily/Larastarters/pull/81). We can work on it together. @PovilasKorop @krekas
