### ISSUE TITLE
Tailwind CSS v3

### ISSUE THREAD

**Issue by stojankukrika** [LaravelDaily/Larastarters#88]
Hi,
I get this after fresh new install in the fresh laravel project even though you say that is not for tailwind 3 or newer(option tailwind (0) and then Windmill theme(0)):
<img width="524" alt="Screenshot 2022-09-14 at 03 37 17" src="https://user-images.githubusercontent.com/10199584/190039367-7d7e708b-0137-4192-8ccd-ccdbcf201b20.png">
What to do with it? Is that OK?

**Comment by PovilasKorop** [comment]
@krekas could you double-check and answer this?

Are we using Tailwind 3 for all Tailwind themes now? 
If so, please make a PR, removing this from readme: "Notice: Tailwind themes are slightly tweaked to work on Tailwind v2."

**Comment by krekas** [comment]
@PovilasKorop all those tailwind themes where made when V3 wasn't out and they might not work or work with errors with V3. In readme there's no saying about V3, just about V2.

**Comment by stojankukrika** [comment]
@krekas I understand but this is what I get on the new installation laravel and after that, I installed Larastarters by selecting Tailwind theme Windmill. Try out with the new laravel project.

**Comment by krekas** [comment]
@stojankukrika I see the problem, breeze installs by default v3 of tailwind. Just downgrade or make theme compatible.

**Comment by PovilasKorop** [comment]
@stojankukrika in other words, Tailwind v3 comes with Laravel Breeze but themes don't use any Tailwind v3 functionality.

So it should not be an issue, but if you see the actual issue of some component or design element not working because of Tailwind version, please report and create a separate issue. Meanwhile I will remove that confusing line from Readme.
